global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # RadBefund+ Backend
  - job_name: 'radbefund-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    # Note: Redis exporter would be needed for detailed Redis metrics

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    # Note: PostgreSQL exporter would be needed for detailed DB metrics
